[project]
name = "scoliotect-backend"
version = "0.1.0"
dependencies = [
    "fastapi",
    "uvicorn",
    "gunicorn",
    "python-multipart",
    "python-dotenv",
    "opencv-python-headless",
    "Pillow",
    "numpy",
    "pandas",
    "scipy",
    "torch",
    "torchvision",
    "ultralytics",
    "requests",
    "tqdm",
    "PyYAML",
    "mat4py",
    "psutil",
    "thop",
]
